version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    container_name: d3_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./mysql/.env
    networks:
      - d3-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: d3_api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - NODE_ENV=development
    env_file:
      - ./api/.env.development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - d3-network

  web:
    build:
      context: ./front
      dockerfile: ./apps/web/Dockerfile
    container_name: d3_web
    ports:
      - "3002:3002"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/assets/node_modules
      - turbo-cache:/app/.turbo
      - /app/.next
      - /app/apps/web/.next
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3000
      - PORT=3002
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - FORCE_COLOR=1
    tty: true
    stdin_open: true
    depends_on:
      - api
    networks:
      - d3-network

networks:
  d3-network:
    driver: bridge

volumes:
  mysql-data:
  turbo-cache:
